#!/bin/sh
set -e

for package in python-dev python-pip python-virtualenv libffi-dev cmake; do
    if [ "$(dpkg --status -- $package|sed -n 's/^Status: //p')" != "install ok installed" ]; then
	# add a space after old values
	missing="${missing:+$missing }$package"
    fi
done
if [ -n "$missing" ]; then
    echo "$0: missing required packages, please install them:" 1>&2
    echo "sudo apt-get install $missing"
    exit 1
fi

if [ -z "$NO_CLOBBER" ] || [ ! -e ./virtualenv ]; then
    # site packages needed because libvirt python bindings are not nicely
    # packaged
    virtualenv --system-site-packages --distribute virtualenv

    # avoid pip bugs
    ./virtualenv/bin/pip install --upgrade pip

    # work-around change in pip 1.5
    ./virtualenv/bin/pip install setuptools --no-use-wheel --upgrade
fi

git submodule sync 
git submodule init
git submodule update

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/samuelj/integration/virtualenv/include"
export LIBGIT2="/home/samuelj/integration/virtualenv"
export LDFLAGS="-Wl,-rpath='$LIBGIT2/lib',--enable-new-dtags $LDFLAGS"

mkdir virtualenv || true
cd libgit2
mkdir build || true
cd build
cmake ..
cmake --build .
cmake .. -DCMAKE_INSTALL_PREFIX=../../virtualenv
cmake --build . --target install
cd ../..

./virtualenv/bin/pip install -r requirements.txt

# forbid setuptools from using the network because it'll try to use
# easy_install, and we really wanted pip; next line will fail if pip
# requirements.txt does not match setup.py requirements -- sucky but
# good enough for now
./virtualenv/bin/python setup.py develop \
    --allow-hosts None
